version: "3.8"

services:
  nuxt:
    build:
      context: .
      target: dev
    working_dir: /src
    volumes:
      - .:/src
      - /src/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_ANON_KEY}
    command: ["npm", "run", "dev"]




